before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags: |
      -X "github.com/chdorner/submarine/cmd.Version={{.Version}}"
      -X "github.com/chdorner/submarine/cmd.CommitSHA={{.ShortCommit}}"
      -X "github.com/chdorner/submarine/cmd.BuildTimestamp={{.Date}}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
